<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>65c816</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>comment</key>
			<string>comment</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.snes</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.line.snes</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>opcodes</string>
			<key>match</key>
			<string>(,|\b(LDA|LDX|LDY|CMP|CPY|CPX|STA|STX|STY|STZ|BCC|BCS|BPL|BMI|BNE|BEQ|BVC|BVS|BRL|BRA|ADC|SBC|INC|INX|INY|DEC|DEX|DEY|SEP|REP|SEC|SED|SEI|CLC|CLD|CLI|CLV|XCE|PEA|PEI|PER|PHA|PHB|PHD|PHK|PHP|PHX|PHY|PLA|PLB|PLD|PLP|PLX|PLY|AND|ASL|BIT|EOR|LSR|ORA|ROL|ROR|TRB|TSB|TAX|TAY|TCD|TCS|TDC|TSC|TSX|TXA|TXS|TXY|TYA|TYX|MVN|MVP|JML|JMP|JSL|JSR|RTI|RTL|RTS|BRK|COP|NOP|STP|WAI|XBA|lda|ldx|ldy|cmp|cpy|cpx|sta|stx|sty|stz|bcc|bcs|bpl|bmi|bne|beq|bvc|bvs|brl|bra|adc|sbc|inc|inx|iny|dec|dex|dey|sep|rep|sec|sed|sei|clc|cld|cli|clv|xce|pea|pei|per|pha|phb|phd|phk|php|phx|phy|pla|plb|pld|plp|plx|ply|and|asl|bit|eor|lsr|ora|rol|ror|trb|tsb|tax|tay|tcd|tcs|tdc|tsc|tsx|txa|txs|txy|tya|tyx|mvn|mvp|jml|jmp|jsl|jsr|rti|rtl|rts|brk|cop|nop|stp|wai|xba|db|org)\b)</string>
			<key>name</key>
			<string>keyword.snes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constants</string>
			<key>match</key>
			<string>(\$|#\$|#)[0-9A-Fa-f]+|(\+|-)[0-9]+</string>
			<key>name</key>
			<string>constant.other.snes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>([\,]|[\[]|[\]]|-)</string>
			<key>name</key>
			<string>keyword.operator.snes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>registers</string>
			<key>match</key>
			<string>\b(x|y|s|a|X|Y|S|A)\b</string>
			<key>name</key>
			<string>variable.parameter.snes</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>labels/directives</string>
			<key>match</key>
			<string>([.])?\w+(:)?</string>
			<key>name</key>
			<string>string.quoted.double.snes</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.snes</string>
	<key>uuid</key>
	<string>d5eb6104-5412-4c50-8e3e-5f2f0baf3d8d</string>
</dict>
</plist>